public class ContainerProduct {

     public List<tempProduct> prodList;
     public class TempProduct {
    
        public integer id;
        public string productName;
        public string ProductCode;
        public string WheelDrive;
        public string Gear;
        public string BodyType;
        public string EngineCapacity;
        public string FuelType;
        public double UnitPrice;
        public string ProductERPId;
        public string Description;
        
        
}
}